theme: minima

title: "Societies of Systems"
subtitle: "A journey into digitization and the engineering of complex systems"
banner: banner.jpg
url: 'https://societies-of-systems.github.io'

author:
  name: Jakob Axelsson

header_pages:
  - about.md
  - jakob-axelsson.md